baseURL = 'https://yossy4411.okayugroup.net/'
languageCode = 'ja'
title = 'yossy4411のノート'
theme = 'stack'
ignoreFiles = ['README.md', 'LICENSE.md', 'content/templates/.*']

defaultContentLanguage = 'ja'