baseURL = 'https://yossy4411.okayugroup.net/'
languageCode = 'ja'
title = 'yossy4411のノート'
theme = 'stack'
ignoreFiles = ['README.md', 'LICENSE.md', 'content/templates/.*']

defaultContentLanguage = 'ja'
copyright = 'yossy4411 (おかゆ)'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
[[menu.main]]
name = "ホーム"
weight = 1
url = "/"
[menu.main.params]
icon = "home"

[[menu.main]]
name = "開発"
weight = 2
url = "/develop/"
[menu.main.params]
icon = "code"

[[menu.main]]
name = "日記"
weight = 3
url = "/diary/"
[menu.main.params]
icon = "pencil"

[[menu.main]]
name = "推し活"
weight = 4
url = "/favorite/"
[menu.main.params]
icon = "star"

[[menu.main]]
name = "おかゆグループ"
weight = 5
url = "/okayugroup/"
[menu.main.params]
icon = "building"

[[menu.main]]
name = "Buy Me a Coffee"
weight = 6
url = "https://www.buymeacoffee.com/yossy4411"
[menu.main.params]
icon = "mug-hot"
newTab = true