name: Check and Update Subtree

on:
  schedule:
    # UTC 21:00 (日本の6時）に実行
    - cron: '0 21 * * *'
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-update-subtree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin main
          git checkout main
          git pull origin main
          
          # debug
          echo "Debugging information:"
          ls -la
          git remote -v
          git branch -a
          git log --oneline -n 5

      - name: Update subtree
        run: |
          git subtree pull --prefix content https://github.com/yossy4411/note.git main
      - name: Commit changes
        run: |
          git add content
          git commit -m "Update note subtree" || echo "No changes to commit"
      - name: Push changes
        run: |
          git push origin main || echo "No changes to push"

  publish:
    runs-on: ubuntu-latest
    needs: check-update-subtree

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Pull changes
        run: |
          git pull origin main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Build
        run: |
          npm install
          npm run quartz build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: yossy4411.okayugroup.net
